# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: jvlsk
# "service" is the name of this project. This will also be added to your AWS resource names.
service: sample-clothing-backend-aws

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  deploymentBucket:
    name: serverless-deployments-sample
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:ListBucket
          Resource:
            - arn:aws:s3:::sample-clothing-images
            - arn:aws:s3:::sample-clothing-images/*
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  #  domain: api.example.com

functions:
  api:
    handler: dist/handler.handler
    events:
      - httpApi: "*"
    environment:
      PORT: "3030"
      ORIGIN: "http://localhost:5173"
      MONGODB_URI: "mongodb+srv://samanseedr2:ntHXai9P3xDFIItF@jvlsk.xxz4bku.mongodb.net/kellyFelder?appName=Jvlsk"
      APP_AWS_REGION: "eu-north-1"
      AWS_S3_BUCKET_NAME: "sample-clothing-images"
